export enum ErrorCode {
  // Generic
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Auth / user lifecycle
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  UNAUTHORIZED_EMAIL = 'UNAUTHORIZED_EMAIL',
  ACCOUNT_EXPIRED = 'ACCOUNT_EXPIRED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Password reset
  TOKEN_REQUIRED = 'TOKEN_REQUIRED',
  INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',
}
