export enum Holiday {
  ROSH_HASHANA = 'ROSH_HASHANA',
  YOM_KIPPUR = 'YOM_KIPPUR',
  SUKKOT = 'SUKKOT',
  SIMCHAT_TORAH = 'SIMCHAT_TORAH',
  HANUKKAH = 'HANUKKAH',
   TU_BISHVAT = 'TU_BISHVAT',
  PURIM = 'PURIM',
    PASSOVER = 'PASSOVER',
    LAG_BAOMER = 'LAG_BAOMER',
  SHAVUOT = 'SHAVUOT',
  SUMMER_VACATION = 'SUMMER_VACATION',
  HASIDIS_EVENT = 'HASIDIS_EVENT'
 }
