export enum Holiday {
  PASSOVER = 'PASSOVER',
  ROSH_HASHANA = 'ROSH_HASHANA',
  YOM_KIPPUR = 'YOM_KIPPUR',
  SUKKOT = 'SUKKOT',
  HANUKKAH = 'HANUKKAH',
  PURIM = 'PURIM',
  SHAVUOT = 'SHAVUOT',
  YOM_HAATZMAUT = 'YOM_HAATZMAUT',
}
